[[scripts]]
name = "greek"
kind = "chart"
capitalize_first = true

[scripts.letters]
"α" = "a"
"β" = "v"
"γ" = "g"
"δ" = "d"
"ε" = "e"
"ζ" = "z"
"η" = "i"
"θ" = "th"
"ι" = "i"
"κ" = "k"
"λ" = "l"
"μ" = "m"
"ν" = "n"
"ξ" = "x"
"ο" = "o"
"π" = "p"
"ρ" = "r"
"σ" = "s"
"ς" = "s"
"τ" = "t"
"υ" = "y"
"φ" = "f"
"χ" = "ch"
"ψ" = "ps"
"ω" = "o"
"ά" = "a"
"έ" = "e"
"ή" = "i"
"ί" = "i"
"ό" = "o"
"ύ" = "y"
"ώ" = "o"
"ϊ" = "i"
"ϋ" = "y"
"ΐ" = "i"
"ΰ" = "y"
