[[scripts]]
name = "khmer"
kind = "chart"
capitalize_first = true

[scripts.letters]
"ក" = "k"
"ខ" = "kh"
"គ" = "k"
"ឃ" = "kh"
"ង" = "ng"
"ច" = "ch"
"ឆ" = "ch"
"ជ" = "j"
"ឈ" = "ch"
"ញ" = "nh"
"ដ" = "d"
"ឋ" = "th"
"ឌ" = "d"
"ឍ" = "th"
"ណ" = "n"
"ត" = "t"
"ថ" = "th"
"ទ" = "d"
"ធ" = "th"
"ន" = "n"
"ប" = "b"
"ផ" = "ph"
"ព" = "p"
"ភ" = "ph"
"ម" = "m"
"យ" = "y"
"រ" = "r"
"ល" = "l"
"វ" = "v"
"ស" = "s"
"ហ" = "h"
"ឡ" = "l"
"អ" = "a"
"ឥ" = "i"
"ឦ" = "i"
"ឧ" = "u"
"ឨ" = "o"
"ឩ" = "u"
"ឪ" = "eu"
"ឫ" = "ru"
"ឬ" = "lu"
"ឭ" = "eu"
"ឯ" = "ae"
"ឰ" = "ai"
"ឱ" = "ao"
"ឲ" = "ao"
"ា" = "a"
"ិ" = "i"
"ី" = "ei"
"ឹ" = "oe"
"ឺ" = "oe"
"ុ" = "o"
"ូ" = "u"
"ួ" = "uo"
"ើ" = "a"
"ឿ" = "oe"
"ៀ" = "ie"
"េ" = "e"
"ែ" = "ae"
"ៃ" = "ai"
"ោ" = "o"
"ៅ" = "au"
"ំ" = "am"
"ះ" = "h"
"ៈ" = ""
"៉" = ""
"៊" = ""
"់" = ""
"៌" = "r"
"៏" = ""
"័" = "a"
"៑" = ""
"្" = ""
"៕" = ""
"ៗ" = ""
"០" = "0"
"១" = "1"
"២" = "2"
"៣" = "3"
"៤" = "4"
"៥" = "5"
"៦" = "6"
"៧" = "7"
"៨" = "8"
"៩" = "9"
