[[scripts]]
name = "lao"
kind = "chart"
capitalize_first = true

[scripts.letters]
"ກ" = "k"
"ຂ" = "kh"
"ຄ" = "kh"
"ງ" = "ng"
"ຈ" = "ch"
"ສ" = "s"
"ຊ" = "s"
"ຍ" = "y"
"ດ" = "d"
"ຕ" = "t"
"ຖ" = "th"
"ທ" = "th"
"ນ" = "n"
"ບ" = "b"
"ປ" = "p"
"ຜ" = "ph"
"ຝ" = "f"
"ພ" = "ph"
"ຟ" = "f"
"ມ" = "m"
"ຢ" = "y"
"ຣ" = "r"
"ລ" = "l"
"ວ" = "w"
"ຫ" = "h"
"ອ" = "o"
"ຮ" = "h"
"ະ" = "a"
"ັ" = "a"
"າ" = "a"
"ຳ" = "am"
"ິ" = "i"
"ີ" = "i"
"ຶ" = "ue"
"ື" = "ue"
"ຸ" = "u"
"ູ" = "u"
"ເ" = "e"
"ແ" = "ae"
"ໂ" = "o"
"ໃ" = "ai"
"ໄ" = "ai"
"ໍ" = "o"
"ົ" = "o"
"ໜ" = "n"
"ໝ" = "m"
"໌" = ""
"່" = ""
"້" = ""
"໊" = ""
"໋" = ""
"ຯ" = ""
"໐" = "0"
"໑" = "1"
"໒" = "2"
"໓" = "3"
"໔" = "4"
"໕" = "5"
"໖" = "6"
"໗" = "7"
"໘" = "8"
"໙" = "9"
