[[scripts]]
name = "thai"
kind = "chart"
capitalize_first = true

[scripts.letters]
"ก" = "k"
"ข" = "kh"
"ฃ" = "kh"
"ค" = "kh"
"ฅ" = "kh"
"ฆ" = "kh"
"ง" = "ng"
"จ" = "ch"
"ฉ" = "ch"
"ช" = "ch"
"ซ" = "s"
"ฌ" = "ch"
"ญ" = "y"
"ฎ" = "d"
"ฏ" = "t"
"ฐ" = "th"
"ฑ" = "th"
"ฒ" = "th"
"ณ" = "n"
"ด" = "d"
"ต" = "t"
"ถ" = "th"
"ท" = "th"
"ธ" = "th"
"น" = "n"
"บ" = "b"
"ป" = "p"
"ผ" = "ph"
"ฝ" = "f"
"พ" = "ph"
"ฟ" = "f"
"ภ" = "ph"
"ม" = "m"
"ย" = "y"
"ร" = "r"
"ฤ" = "ru"
"ล" = "l"
"ฦ" = "lu"
"ว" = "w"
"ศ" = "s"
"ษ" = "s"
"ส" = "s"
"ห" = "h"
"ฬ" = "l"
"อ" = "o"
"ฮ" = "h"
"ะ" = "a"
"ั" = "a"
"า" = "a"
"ำ" = "am"
"ิ" = "i"
"ี" = "i"
"ึ" = "ue"
"ื" = "ue"
"ุ" = "u"
"ู" = "u"
"เ" = "e"
"แ" = "ae"
"โ" = "o"
"ใ" = "ai"
"ไ" = "ai"
"็" = ""
"่" = ""
"้" = ""
"๊" = ""
"๋" = ""
"์" = ""
"ํ" = "m"
"ฯ" = ""
"๐" = "0"
"๑" = "1"
"๒" = "2"
"๓" = "3"
"๔" = "4"
"๕" = "5"
"๖" = "6"
"๗" = "7"
"๘" = "8"
"๙" = "9"
