//! Scans `romanize/*.toml` (skipping `template.toml`) and writes a generated
//! file containing the raw TOML strings as Rust literals, which
//! `src/romanize.rs` includes at compile time.

use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/romanize/");

    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let dir = Path::new(&manifest).join("src/romanize");

    let mut names: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("toml") {
                let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
                if stem != "template" {
                    names.push(stem.to_string());
                }
            }
        }
    }
    names.sort();

    let mut code =
        String::from("/// Auto-generated by build.rs — do not edit.\npub fn romanize_data() -> &'static [(&'static str, &'static str)] {\n    &[\n");
    for name in &names {
        let toml = fs::read_to_string(dir.join(format!("{name}.toml"))).unwrap();
        // Triple-hash raw strings tolerate # inside TOML comments.
        code.push_str(&format!("        (\"{name}\", r###\"{toml}\"###),\n"));
    }
    code.push_str("    ]\n}\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("romanize_index.rs"), &code).unwrap();
}
